version: '3.8'
services:
  users:
    build: ./users-service
    ports:
      - "3001:3001"
    environment:
      - DB_URI=mongodb://mongo:27017
  products:
    build: ./products-service
    ports:
      - "3002:3002"
    environment:
      - DB_URI=mongodb://mongo:27017
  orders:
    build: ./orders-service
    ports:
      - "3003:3003"
    environment:
      - DB_URI=mongodb://mongo:27017
  reviews:
    build: ./reviews-service
    ports:
      - "3004:3004"
    environment:
      - DB_URI=mongodb://mongo:27017
  categories:
    build: ./categories-service
    ports:
      - "3005:3005"
    environment:
      - DB_URI=mongodb://mongo:27017
  cart:
    build: ./cart-service
    ports:
      - "3006:3006"
    environment:
      - DB_URI=mongodb://mongo:27017
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
